<%@ Page Language="vb" AutoEventWireup="false" Codebehind="1 Determining Fair Market Value.aspx.vb" Inherits="Brinkster._1_Determining_Fair_Market_Value"%>
<%@ Register TagPrefix="uc1" TagName="ResourcesContact" Src="../../Controls/ResourcesContact.ascx" %>
<%@ Register TagPrefix="uc1" TagName="Left" Src="../../Controls/Left.ascx" %>
<%@ Register TagPrefix="uc1" TagName="Right" Src="../../Controls/Right.ascx" %>
<%@ Register TagPrefix="uc1" TagName="Header" Src="../../Controls/Header.ascx" %>
<%@ Register TagPrefix="uc1" TagName="Footer" Src="../../Controls/Footer.ascx" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>Determining Fair Market Value</title>
		<meta name="GENERATOR" content="Microsoft Visual Studio .NET 7.1">
		<meta name="CODE_LANGUAGE" content="Visual Basic .NET 7.1">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</HEAD>
	<body>
		<form id="Form1" method="post" runat="server">
			<TABLE id="Table4" cellSpacing="0" cellPadding="0" width="95%" border="0">
				<TR>
					<TD vAlign="top" align="center"></TD>
					<TD vAlign="top" align="center" width="10" height="10">&nbsp;</TD>
					<TD vAlign="top" align="left" height="10">
						<uc1:Header id="Header1" runat="server"></uc1:Header></TD>
					<TD vAlign="top" align="center" width="10" height="10"></TD>
					<TD vAlign="top" align="center"></TD>
				</TR>
				<TR>
					<TD vAlign="top">
						<uc1:Left id="Left1" runat="server"></uc1:Left></TD>
					<TD vAlign="top"></TD>
					<TD vAlign="top" width="100%">
						<h3>Determining Fair Market Value</h3>
						<p><FONT size="2"><STRONG>(Reading time: 125 seconds)</STRONG></FONT>
						<P>
						Dear Prospective Seller,
						<p>
						Now that you have decided to sell your home, it is time to determine the list 
						price. It is essential to list your home at the right price and it is important 
						to get it right the first time. The pricing of a house is a major component in 
						ensuring that your home sells quickly.
						<p>
						There are several ways to determine the market value of your home, including an 
						Automated Valuation Model, Comparable Market Analysis and Appraisal. An 
						Automated Valuation Model is an electronic appraiser that provides a Homes 
						Sales Valuation Report by entering your property address. A Comparable Market 
						Analysis is generated by comparing prices of similar properties in your area 
						that have recently sold, are currently on-the-market or were taken off the 
						market unsold. Unlike a Comparable Market Analysis, which is often obtained at 
						no cost, an Appraisal is completed by a professional appraiser specifically for 
						your home and costs between $200 and $300. After inspection, the appraiser will 
						determine the value of your home based on its condition, location and a 
						Comparable Market Analysis of sold properties in your area. This article 
						includes tools for establishing the market value of your home. Together, we 
						will agree upon the price that is right for your house.
						<p><b>Tips for Setting the Price</b>
						<p><b>1. Abandon your Personal Bias</b><br>
						In order to determine the market value of your home, you must objectively 
						establish what someone else would pay for your house. This means setting aside 
						your emotional attachment to the many wonderful memories you have shared in 
						your home. Some things to consider when determining the price of your home: 
						total square footage, floor plan, construction quality, condition, amenities, 
						lot size, topography, view, landscaping and neighborhood.
						<p><b>2. Educate Yourself</b><br>
						Visit local open houses and compare the location, condition, size and amenities 
						of these houses to your own as objectively as possible. If your house is 
						located in a neighborhood that is highly in demand, you will be able to get a 
						higher price than you can for the same house in a less desirable area. A house 
						that has been well-maintained will show better and, therefore, is likely to 
						sell more promptly and for a higher price than one that needs work. When a 
						house offers amenities that are currently popular in the marketplace, it will 
						invite a higher price.
						<p><b>3. Get Comparable Market Analysis from your Real Estate Agent</b><br>
						As your real estate agent, I will give you a full Comparable Market Analysis 
						after examining what comparable homes have sold for in your neighborhood in the 
						recent past. Drawing upon my knowledge of other homes within the area, I will 
						determine what I believe to be an approximate value of your home that we may 
						use together to determine the final listing price.
						<p><b>4. Calculate the Price per Square Foot</b><br>
						Using homes from the Comparable Market Analysis, divide the list price by the 
						total square footage. This will establish a baseline value per square foot of 
						homes in your area. Multiply this number by the total square footage of your 
						house and adjust based on amenities.
						<p><b>5. Consider Market Conditions</b><br>
						How is the economy? Interest rates? Local job market? What season is it? Homes 
						tend to sell more quickly in the Spring and Summer months than in the Winter 
						because people prefer to move during the longer warmer days and between school 
						years. Are prices of homes in your neighborhood on the rise? Are they selling 
						quickly? Check your Comparative Market Analysis to determine the days on the 
						market for each comparable house sold. When real estate is booming, houses may 
						sell in a few days. Ask your local real estate agent if it is a buyer’s or 
						seller’s market. The Unsold Inventory Index, which indicates the pace of the 
						market, is calculated by measuring how long it would take for all the homes 
						currently on the market to be sold at the current rate of sales. A smaller 
						index signifies a seller’s market, whereas a higher index suggests a buyer’s 
						market. The Price Discount is the percentage difference between the seller's 
						initial asking price and what the house actually sold for. A small percentage 
						means the market favors sellers, while a large average discount signals a 
						buyer's market.
						<p><b>6. Offer Incentives</b><br>
							Be creative and flexible in meeting the buyer’s needs. For example, offering a 
							short escrow will attract buyers who want to move immediately. You might 
							propose paying the buyer’s closing costs to seal the deal. Cash incentives will 
							help first-time buyers who need assistance with their down payment.</p>
						<P>
							<uc1:ResourcesContact id="ResourcesContact1" runat="server"></uc1:ResourcesContact></P>
					</TD>
					<TD vAlign="top">
						<uc1:Right id="Right1" runat="server"></uc1:Right></TD>
					<TD style="WIDTH: 100px" vAlign="top"></TD>
				</TR>
				<TR>
					<TD height="10"></TD>
					<TD align="center" height="10"></TD>
					<TD align="center" height="10">
						<uc1:Footer id="Footer1" runat="server"></uc1:Footer></TD>
					<TD align="center" height="10"></TD>
					<TD align="center" height="10"></TD>
				</TR>
			</TABLE>
			&nbsp;
		</form>
	</body>
</HTML>
