'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''reStudioHeader class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class reStudioHeader

    '''<summary>
    '''pnlAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAbout As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlListings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlSoldReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSoldReports As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResources As Global.System.Web.UI.WebControls.Panel
End Class
